### PR TITLE
 fix logon process by adding cookie support to axios

### PR DESCRIPTION
**Pull request by TezzM0**
I was able to successfully log in and get stats and data by taking the changes made in `login.js` and adding cookie support to axios with axios-cookiejar-support [https://www.npmjs.com/package/axios-cookiejar-support]

### CODE REVIEW

**Comment by Lierrmm** [comment]
Can this be reproducible without puppeteer? Ideally, I do not want to be using puppeteer in the library as it will increase the size of the module.

**Comment by TezzM0** [comment]
I had a go at trying to remove it by making an axios get request and trying to pull the cookies out, but I wasn't successful.

**Comment by Lierrmm** [comment]
I'm merging into a new branch to stop any conflicts with master for now until I can find a solution for no puppeteer

**Comment by Lierrmm** [comment]
This has been merged into https://www.npmjs.com/package/call-of-duty-api/v/2.0.0-dev

Thank you for the PR. has helped a lot.

**Pull request merged**
